### ISSUE TITLE
Create a bitwrap-etk binding repo?

### ISSUE THREAD

**Issue by codecakes** [bitwrap/bitwrap-io#2]
@stackdump  this will have the binding functions, aux functions. you could directly call this using npm and import it in bitwrap for modularity and better abstraction. I can create and work on this repo given test input output instance have been provided here #1

**Comment by stackdump** [comment]
@codecakes I added   bitwrap-io-etk which would be the final integration environment for build/deploy.
Integration here would be similar to : https://github.com/bitwrap/bitwrap-io/blob/8873e2f215355791910a434eaeadf32d4ed7cb8b/lib/bitwrap-io.js

I also added bitwrap-storage-etk which is where I was planning on adding a facade in front of etk to conform to the API produced as part of the bitwrap-storage-nodegit module - this is likely were the main integration between bw/etk should live

**Comment by codecakes** [comment]
@stackdump  so [bitwrap-io-etk](https://github.com/bitwrap/bitwrap-io-etk) is the integration layer correct?

I didn't understand what is the role of [bitwrap-storage-nodegit](https://github.com/bitwrap/bitwrap-storage-nodegit) ? storing transactions?

**Comment by stackdump** [comment]
yes - I'm thinking bitwrap-io-etk as the place where bitwrap-npm, bitwrap-storage-etk are used.

the storeage-nodegit repo is kindof used as a blockchain analog - initially I didn't want to code against actual blockchain APIs so that's what I targeted first.

The idea was that I'd keep a full history using git as a ledger & then propagate that data to actual blockchains. - The git repo it writes to would serve as a index that we could use to read blockchain data - and a user can choose to keep this private or host in the open
